apps/account/urls.py
from django.urls import path

from . import views
app_name = 'account'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_request, name='login'),
    path('student_register/', views.StudentRegister, name='student_register'),
    path('coordinator_register/', views.CoordinatorRegister, name='coordinator_register'),
    path('logout/', views.logout, name='logout')
]

apps/core/urls.py
from django import urls
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('', views.frontpage, name="frontpage"),
    path('student/Dashboard/', views.StudentDashboard, name="student-dashboard"),
    path('coordinator/Dashboard/', views.coordinatorDashboard, name="coordinator-dashboard"),
]

apps/event/urls.py
from django.urls import path
from django.urls import path

from .views import EventList

urlpatterns = [
    path('list/', EventList, name='event-list')
]

viper/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('apps.account.urls')),
    path('', include('apps.core.urls')),
    path('events/', include('apps.event.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    is_coordinator = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)
    first_name = models.CharField(max_length=100)
    last_name =  models.CharField(max_length=100)


class Coordinator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    phone = models.CharField(max_length=20)
    department = models.CharField(max_length=200)
    def __str__(self):
        return f"{self.username}"

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    phone = models.CharField(max_length=20)
    department = models.CharField(max_length=200)
    def __str__(self):
        return f"{self.user}"

apps/core/models.py
from django.db import models

# Create your models here.

apps/event/models.py
from django.db import models
from django.db.models.fields import IntegerField
from django.utils.translation import gettext_lazy as _
from django_quill.fields import QuillField

from apps.account.models import Student
class Event(models.Model):
    title = models.CharField(_("title"), max_length=200)
    description = QuillField("add description")
    start_date = models.DateField()
    duration = IntegerField(default=1)
    price = IntegerField(default=0, blank=True, null=True)
    photo = models.ImageField(upload_to='event-images/', null=True, blank=True)
    venue = models.CharField(max_length=255)
    max_enroll = models.IntegerField(default=0)
    #platforms = models.CharField(choices=PLATFORM, max_length=10)

    def __str__(self):
        return self.title

class RegisterEvent(models.Model):
    events = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(Student, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=13)
    email = models.EmailField()

    def __str__(self) -> str:
        return self.user.username

apps/account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.db import transaction
from .models import User,Student,Coordinator

class StudentSignUpForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    phone_number = forms.CharField(required=True)
    location = forms.CharField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User
    
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student  = True
        user.first_name = self.cleaned_data.get('first_name')
        user.last_name = self.cleaned_data.get('last_name')
        user.save()
        customer = Student.objects.create(user=user)
        customer.phone_number=self.cleaned_data.get('phone_number')
        customer.location=self.cleaned_data.get('location')
        customer.save()
        return user

class CoordinatorSignUpForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    phone_number = forms.CharField(required=True)
    

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_coordinator = True
        user.is_staff = True
        user.first_name = self.cleaned_data.get('first_name')
        user.last_name = self.cleaned_data.get('last_name')
        user.save()
        employee = Coordinator.objects.create(user=user)
        employee.phone_number=self.cleaned_data.get('phone_number')
        employee.save()
        return user

apps/event/forms.py
from apps.event.models import Event
from django import forms

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = '__all__'
    

apps/account/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect, render, HttpResponse
from django.views.generic import CreateView
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .models import User
from .forms import StudentSignUpForm, CoordinatorSignUpForm

def register(request):
    return render(request, 'accounts/index.html')

"""
class StudentRegister(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'accounts/student_register.html'

    def validate(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')
"""

def StudentRegister(request):
    form = StudentSignUpForm()
    if request.method == "POST":
        form = StudentSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('account:login')
    return render(request, 'accounts/student_register.html', {'form':form})


def CoordinatorRegister(request):
    form = CoordinatorSignUpForm()
    if request.method == "POST":
        form = CoordinatorSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('account:login')
    return render(request, 'accounts/coordinator-register.html', {'form':form})


def login_request(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None :
                login(request, user)
                if user.is_student:
                    return redirect('core:student-dashboard')
                   #return HttpResponse("Student view")
                elif user.is_coordinator:
                    return redirect('core:coordinator-dashboard')
            else:
                messages.error(request,"Invalid username or password")
        else:
                messages.error(request,"Invalid username or password")
    return render(request, 'accounts/login.html',
    context={'form':AuthenticationForm()})

def logout_view(request):
    logout(request)
    return redirect('/')

apps/core/views.py
from django.shortcuts import render

def frontpage(request):
    return render(request, 'core/index.html')

def StudentDashboard(request):
    return render(request, 'core/studentView/student_dashboard.html')

def coordinatorDashboard(request):
    return render(request, 'core/coordinatorView/coordinator_dashboard.html')

apps/event/views.py
from apps.event.forms import EventForm
from django.shortcuts import render

from apps.event.models import Event


# Create your views here.
def EventList(request):
    events = Event.objects.all()
    context = {
        'events': events
    }
    return render( request, 'events/event-list.html', context)

apps/account/templates/accounts/coordinator-register.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <title>Demo Registration</title>
</head>
<body>

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Coordinator Register</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'account:coordinator_register' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% for error in field.errors %}
                                      <span style="color:red">{{ error }}</span>
                                    {% endfor %}
                         {% endfor %}
                             <input type="submit" value="Register" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>

</body>
</html>

apps/account/templates/accounts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
</head>
<body>
    <h1>Home</h1>
    <a href="{% url 'account:student_register' %}"><button class="primary">Student Register</button></a>
    <a href="{% url 'account:coordinator_register' %}"><button class="primary">Coordinator Register</button></a>
    <a href="{% url 'account:login' %}"><button class="primary">Login</button></a>
</body>
</html>

apps/account/templates/accounts/login.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <title>Demo Registration</title>
</head>
<body>

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Login</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'account:login' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% if messages%}
                                      {% for message in messages %}
                                        <span style="color:red">{{ message }}</span>
                                      {% endfor %}
                                     {% endif %}
                         {% endfor %}
                         <br>
                             <input type="submit" value="Login" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>

</body>
</html>

apps/account/templates/accounts/student_register.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <title>Demo Registration</title>
</head>
<body>
  <br>
  <br>
  <br>
    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Student Register</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'account:student_register' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% for error in field.errors %}
                                      <span style="color:red">{{ error }}</span>
                                    {% endfor %}
                         {% endfor %}
                             <input type="submit" value="Register" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>

</body>
</html>

apps/core/templates/core/coordinatorView/coordinator_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard | Viper</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'Dashboard/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'Dashboard/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light">Viper</div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Dashboard</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Event Managment</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                      </div>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Profile</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Status</a>
                </div>
            </div>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        <button class="btn btn-primary" id="sidebarToggle"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-right" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M1 11.5a.5.5 0 0 0 .5.5h11.793l-3.147 3.146a.5.5 0 0 0 .708.708l4-4a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 11H1.5a.5.5 0 0 0-.5.5zm14-7a.5.5 0 0 1-.5.5H2.707l3.147 3.146a.5.5 0 1 1-.708.708l-4-4a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 4H14.5a.5.5 0 0 1 .5.5z"/>
                          </svg></button>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                                <li class="nav-item active"><a class="nav-link" href="{% url 'core:student-dashboard' %}">Home</a></li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="#!">View Profile</a>
                                        <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
                                        
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#!">Something else here</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- Page content-->
                <div class="container-fluid">
                    <h1 class="mt-4 text-center p-3">Coordinator Dashboard</h1>
                    
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-xs-1 col-sm-6 col-md-4">
                                <div class="card">
                                    <h1 class="title text-center">Events</h1>
                                    <hr>
                                    <button class="btn btn-secondary btn-lg" type="button">
                                      
                                        <div class="card-body">
                                            <h3 class="card-title text-center">
                                                Upcomming Events
                                            </h3>
                                            <p class="card-text">
                                                Event Information
                                            </p>
                                            <a href="#" class="btn btn-primary">Enroll</a>
                                        </div>
                                     </button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'Dashboard/js/scripts.js' %}"></script>
    </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Viper</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'Anyar/assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'Anyar/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'Anyar/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'Anyar/assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'Anyar/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'Anyar/assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'Anyar/assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'Anyar/assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'Anyar/assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'Anyar/assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'Anyar/assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Anyar - v2.2.1
  * Template URL: https://bootstrapmade.com/anyar-free-multipurpose-one-page-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

    <!--
   ======= Top Bar ======= 
  <div id="topbar" class="d-none d-lg-flex align-items-center fixed-top ">
    <div class="container d-flex align-items-center">
      <div class="contact-info mr-auto">
        <ul>
          <li><i class="icofont-envelope"></i><a href="mailto:contact@example.com">contact@example.com</a></li>
          <li><i class="icofont-phone"></i> +1 5589 55488 55</li>
          <li><i class="icofont-clock-time icofont-flip-horizontal"></i> Mon-Fri 9am - 5pm</li>
        </ul>
      </div>
      <div class="cta">
        <a href="#about" class="scrollto">Get Started</a>
      </div>
    </div>
  </div>
-->
  <!-- ======= Header ======= -->
  <div id="topbar" class="d-none d-lg-flex align-items-center fixed-top ">
  <header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center">

      <h1 class="logo mr-auto"><a href="#header" class="scrollto">Viper</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="#header" class="logo mr-auto scrollto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="#header">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#services">Services</a></li>
          
          <li><a href="#team">Team</a></li>
          
          
          <li class="drop-down"><a href="">Registration</a>
            <ul>
              <li><a href="{% url 'account:student_register' %}">Student Registration</a></li>
               <!--<li class="drop-down"><a href="#">Deep Drop Down</a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                  <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
                </ul>
              </li>-->
              <li><a href="{% url 'account:coordinator_register' %}">Coordinator Registration</a></li>
              
            </ul>
          </li>
          <li><a href="{% url 'account:login' %}">Login</a></li>
          <li><a href="#contact">Contact</a></li>

        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->
</div>

  {% block content %}
  {% endblock content %}

  
  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-newsletter">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
          </div>
          <div class="col-lg-6">
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>

          </div>

          <div class="col-lg-3 col-md-6 footer-info">
            <h3>About Anyar</h3>
            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Anyar</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/anyar-free-multipurpose-one-page-bootstrap-theme/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'Anyar/assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'Anyar/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'Anyar/assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'Anyar/assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'Anyar/assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'Anyar/assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'Anyar/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'Anyar/assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'Anyar/assets/js/main.js' %}"></script>

</body>

</html>